-- Run this in your Supabase SQL Editor to create the testimonials table
create table testimonials (
  id bigint generated by default as identity primary key,
  name text not null,
  role text,
  text text not null,
  rating smallint default 5 check (rating >= 1 and rating <= 5),
  featured boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Enable Row Level Security
alter table testimonials enable row level security;

-- Allow public read access (for the frontend)
create policy "Anyone can view testimonials"
  on testimonials for select
  using (true);

-- Allow authenticated users full access (admin dashboard)
create policy "Authenticated users can manage testimonials"
  on testimonials for all
  using (auth.role() = 'authenticated');
