-- ADMIN DASHBOARD DATABASE FIX V2
-- This script fixes the "fileUrl" errors and ensures all Admin sections save correctly.

-- 1. Library Resources Table Fix
-- Rename public.resources to public.library_resources if it exists, or create it.
DO $$ 
BEGIN 
    IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = 'resources') AND 
       NOT EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = 'library_resources') THEN
        ALTER TABLE public.resources RENAME TO library_resources;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.library_resources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    type TEXT DEFAULT 'PERL',
    category TEXT DEFAULT 'Governance',
    description TEXT,
    file_url TEXT,
    status TEXT DEFAULT 'Published',
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Ensure file_url column exists and handle camelCase fallback
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='library_resources' AND COLUMN_NAME='file_url') THEN
        ALTER TABLE public.library_resources ADD COLUMN file_url TEXT;
    END IF;
END $$;

-- 2. Books Table Fix
CREATE TABLE IF NOT EXISTS public.books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    summary TEXT,
    image_url TEXT,
    file_url TEXT,
    status TEXT DEFAULT 'Published',
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 3. Workshops Tables
CREATE TABLE IF NOT EXISTS public.workshops (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    date TEXT,
    time TEXT,
    host TEXT,
    format TEXT DEFAULT 'Virtual',
    status TEXT DEFAULT 'Upcoming',
    location TEXT,
    capacity INTEGER DEFAULT 50,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.workshop_registrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workshop_id BIGINT REFERENCES public.workshops(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    full_name TEXT,
    email TEXT,
    role TEXT,
    reason TEXT,
    registered_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE(workshop_id, user_id)
);

-- 4. RLS Policies for new tables
ALTER TABLE public.library_resources ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.books ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.workshops ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.workshop_registrations ENABLE ROW LEVEL SECURITY;

-- Select policies
DROP POLICY IF EXISTS "Public Select Resources" ON public.library_resources;
CREATE POLICY "Public Select Resources" ON public.library_resources FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Select Books" ON public.books;
CREATE POLICY "Public Select Books" ON public.books FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Select Workshops" ON public.workshops;
CREATE POLICY "Public Select Workshops" ON public.workshops FOR SELECT USING (true);

-- Admin Management policies
DROP POLICY IF EXISTS "Admin Manage Resources" ON public.library_resources;
CREATE POLICY "Admin Manage Resources" ON public.library_resources FOR ALL USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND (role = 'Admin' OR role = 'admin'))
);

DROP POLICY IF EXISTS "Admin Manage Books" ON public.books;
CREATE POLICY "Admin Manage Books" ON public.books FOR ALL USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND (role = 'Admin' OR role = 'admin'))
);

DROP POLICY IF EXISTS "Admin Manage Workshops" ON public.workshops;
CREATE POLICY "Admin Manage Workshops" ON public.workshops FOR ALL USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND (role = 'Admin' OR role = 'admin'))
);

-- 4b. RLS Policies for chapters and modules (needed for course editing)
ALTER TABLE IF EXISTS public.chapters ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.modules ENABLE ROW LEVEL SECURITY;

-- Public can read chapters/modules for published courses
DROP POLICY IF EXISTS "Public Select Chapters" ON public.chapters;
CREATE POLICY "Public Select Chapters" ON public.chapters FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.courses WHERE id = course_id AND status = 'Published')
);

DROP POLICY IF EXISTS "Public Select Modules" ON public.modules;
CREATE POLICY "Public Select Modules" ON public.modules FOR SELECT USING (true);

-- Admins can do everything on chapters and modules
DROP POLICY IF EXISTS "Admin Manage Chapters" ON public.chapters;
CREATE POLICY "Admin Manage Chapters" ON public.chapters FOR ALL USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND (role = 'Admin' OR role = 'admin'))
);

DROP POLICY IF EXISTS "Admin Manage Modules" ON public.modules;
CREATE POLICY "Admin Manage Modules" ON public.modules FOR ALL USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND (role = 'Admin' OR role = 'admin'))
);

-- Also ensure courses table allows admin ALL operations
DROP POLICY IF EXISTS "Admin Manage Courses" ON public.courses;
CREATE POLICY "Admin Manage Courses" ON public.courses FOR ALL USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND (role = 'Admin' OR role = 'admin'))
);

-- 5. Fix Profile Role Consistency
-- Aggressively drop ANY constraint that could be blocking the update
DO $$ 
BEGIN 
    -- Drop all known constraint names that might exist
    ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_role_check;
    ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_role_final_check;
    ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_role_standard_check;
    
    -- Drop anonymous constraints if possible (Postgres doesn't make this easy without dynamic SQL,
    -- but usually 'profiles_role_check' is the default name).
    -- If there's still a violation, it might be an anonymous one we missed.

    -- Standardize existing roles to lowercase
    UPDATE public.profiles SET role = 'learner' WHERE LOWER(role) = 'learner';
    UPDATE public.profiles SET role = 'admin' WHERE LOWER(role) = 'admin';
    UPDATE public.profiles SET role = 'instructor' WHERE LOWER(role) = 'instructor';
    
    -- Default any unknown roles to 'learner'
    UPDATE public.profiles SET role = 'learner' 
    WHERE role NOT IN ('learner', 'instructor', 'admin', 'Admin');

    -- Now apply the final, clean constraint
    ALTER TABLE public.profiles ADD CONSTRAINT profiles_role_final_check CHECK (role IN ('learner', 'instructor', 'admin', 'Admin'));
END $$;
