-- ============================================================================
-- ADMIN DATABASE FIX V2 (COMPREHENSIVE)
-- Run this ONCE in the Supabase SQL Editor. It fixes ALL known issues.
-- ============================================================================

-- ─── 1. LIBRARY RESOURCES TABLE ─────────────────────────────────────────────
DO $$ 
BEGIN 
    IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = 'resources') AND 
       NOT EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = 'library_resources') THEN
        ALTER TABLE public.resources RENAME TO library_resources;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.library_resources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    type TEXT DEFAULT 'PERL',
    category TEXT DEFAULT 'Governance',
    description TEXT,
    file_url TEXT,
    status TEXT DEFAULT 'Published',
    created_at TIMESTAMPTZ DEFAULT now()
);

DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='library_resources' AND COLUMN_NAME='file_url') THEN
        ALTER TABLE public.library_resources ADD COLUMN file_url TEXT;
    END IF;
END $$;

-- ─── 2. BOOKS TABLE ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    summary TEXT,
    image_url TEXT,
    file_url TEXT,
    status TEXT DEFAULT 'Published',
    created_at TIMESTAMPTZ DEFAULT now()
);

-- ─── 3. WORKSHOPS TABLES ────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.workshops (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    date TEXT,
    time TEXT,
    host TEXT,
    format TEXT DEFAULT 'Virtual',
    status TEXT DEFAULT 'Upcoming',
    location TEXT,
    capacity INTEGER DEFAULT 50,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.workshop_registrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workshop_id BIGINT REFERENCES public.workshops(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    full_name TEXT,
    email TEXT,
    role TEXT,
    reason TEXT,
    registered_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE(workshop_id, user_id)
);

-- ─── 4. USER NOTES TABLE (for learn player) ────────────────────────────────
DROP TABLE IF EXISTS public.user_notes CASCADE;
CREATE TABLE public.user_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    course_id BIGINT NOT NULL,
    module_id BIGINT NOT NULL,
    note_text TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE(user_id, module_id)
);

-- ─── 5. DISCUSSIONS TABLE (for learn player) ────────────────────────────────
DROP TABLE IF EXISTS public.discussions CASCADE;
CREATE TABLE public.discussions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    course_id BIGINT NOT NULL,
    module_id BIGINT NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- ─── 6. USER PROGRESS TABLE (for learn player) ─────────────────────────────
DROP TABLE IF EXISTS public.user_progress CASCADE;
CREATE TABLE public.user_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    course_id BIGINT NOT NULL,
    module_id BIGINT NOT NULL,
    completed BOOLEAN DEFAULT false,
    watched_seconds INTEGER DEFAULT 0,
    status TEXT DEFAULT 'not-started',
    created_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE(user_id, module_id)
);

-- ============================================================================
-- 7. ENABLE RLS ON ALL TABLES
-- ============================================================================
ALTER TABLE public.library_resources ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.books ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.workshops ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.workshop_registrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.course_modules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.discussions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_progress ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- 8. DROP ALL OLD/CONFLICTING POLICIES FIRST (from schema.sql etc.)
-- ============================================================================
-- Courses
DROP POLICY IF EXISTS "Published courses are viewable" ON public.courses;
DROP POLICY IF EXISTS "Admins manage courses" ON public.courses;
DROP POLICY IF EXISTS "Public Select Courses" ON public.courses;
DROP POLICY IF EXISTS "Admin Manage Courses" ON public.courses;

-- Course Modules
DROP POLICY IF EXISTS "Modules viewable with course" ON public.course_modules;
DROP POLICY IF EXISTS "Admins manage modules" ON public.course_modules;
DROP POLICY IF EXISTS "Public Select Course Modules" ON public.course_modules;
DROP POLICY IF EXISTS "Admin Manage Course Modules" ON public.course_modules;

-- Resources
DROP POLICY IF EXISTS "Published resources are viewable" ON public.resources;
DROP POLICY IF EXISTS "Admins manage resources" ON public.resources;
DROP POLICY IF EXISTS "Public Select Resources" ON public.library_resources;
DROP POLICY IF EXISTS "Admin Manage Resources" ON public.library_resources;

-- Books
DROP POLICY IF EXISTS "Published books are viewable" ON public.books;
DROP POLICY IF EXISTS "Admins manage books" ON public.books;
DROP POLICY IF EXISTS "Public Select Books" ON public.books;
DROP POLICY IF EXISTS "Admin Manage Books" ON public.books;

-- Workshops
DROP POLICY IF EXISTS "Public Select Workshops" ON public.workshops;
DROP POLICY IF EXISTS "Admin Manage Workshops" ON public.workshops;

-- ============================================================================
-- 9. CREATE CLEAN POLICIES
-- ============================================================================

-- ── Courses: everyone reads, admins manage ──
CREATE POLICY "Public Select Courses" ON public.courses FOR SELECT USING (true);
CREATE POLICY "Admin Manage Courses" ON public.courses FOR ALL
  USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND LOWER(role) = 'admin'))
  WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND LOWER(role) = 'admin'));

-- ── Course Modules: everyone reads, admins manage ──
CREATE POLICY "Public Select Course Modules" ON public.course_modules FOR SELECT USING (true);
CREATE POLICY "Admin Manage Course Modules" ON public.course_modules FOR ALL
  USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND LOWER(role) = 'admin'))
  WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND LOWER(role) = 'admin'));

-- ── Library Resources: everyone reads, admins manage ──
CREATE POLICY "Public Select Resources" ON public.library_resources FOR SELECT USING (true);
CREATE POLICY "Admin Manage Resources" ON public.library_resources FOR ALL
  USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND LOWER(role) = 'admin'))
  WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND LOWER(role) = 'admin'));

-- ── Books: everyone reads, admins manage ──
CREATE POLICY "Public Select Books" ON public.books FOR SELECT USING (true);
CREATE POLICY "Admin Manage Books" ON public.books FOR ALL
  USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND LOWER(role) = 'admin'))
  WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND LOWER(role) = 'admin'));

-- ── Workshops: everyone reads, admins manage ──
CREATE POLICY "Public Select Workshops" ON public.workshops FOR SELECT USING (true);
CREATE POLICY "Admin Manage Workshops" ON public.workshops FOR ALL
  USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND LOWER(role) = 'admin'))
  WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND LOWER(role) = 'admin'));

-- ── User Notes: users manage own notes ──
DROP POLICY IF EXISTS "Users manage own notes" ON public.user_notes;
CREATE POLICY "Users manage own notes" ON public.user_notes FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- ── Discussions: everyone reads, users create own ──
DROP POLICY IF EXISTS "Public read discussions" ON public.discussions;
CREATE POLICY "Public read discussions" ON public.discussions FOR SELECT USING (true);
DROP POLICY IF EXISTS "Users create discussions" ON public.discussions;
CREATE POLICY "Users create discussions" ON public.discussions FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- ── User Progress: users manage own progress ──
DROP POLICY IF EXISTS "Users manage own progress" ON public.user_progress;
CREATE POLICY "Users manage own progress" ON public.user_progress FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- ============================================================================
-- 10. FIX PROFILE ROLE CONSISTENCY
-- ============================================================================
DO $$ 
BEGIN 
    ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_role_check;
    ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_role_final_check;
    ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_role_standard_check;

    UPDATE public.profiles SET role = 'learner' WHERE LOWER(role) = 'learner';
    UPDATE public.profiles SET role = 'admin' WHERE LOWER(role) = 'admin';
    UPDATE public.profiles SET role = 'instructor' WHERE LOWER(role) = 'instructor';
    
    UPDATE public.profiles SET role = 'learner' 
    WHERE role NOT IN ('learner', 'instructor', 'admin');

    ALTER TABLE public.profiles ADD CONSTRAINT profiles_role_final_check 
      CHECK (role IN ('learner', 'instructor', 'admin'));
END $$;
