-- FINAL DATABASE FIX SCRIPT (Corrected for BigInt IDs)
-- RUN THIS IN YOUR SUPABASE SQL EDITOR

-- 1. Remove the broken chapters table if it was created with the wrong ID type
DROP TABLE IF EXISTS public.chapters CASCADE;

-- 2. Create Chapters table with bigint ID (to match courses table)
CREATE TABLE public.chapters (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id bigint REFERENCES public.courses(id) ON DELETE CASCADE NOT NULL,
    title text NOT NULL,
    sequence_order integer DEFAULT 0,
    created_at timestamp with time zone DEFAULT now()
);

-- 3. Update Modules table (Add chapter_id and description)
DO $$ 
BEGIN 
    -- Add chapter_id as bigint
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='modules' AND COLUMN_NAME='chapter_id') THEN
        ALTER TABLE public.modules ADD COLUMN chapter_id bigint REFERENCES public.chapters(id) ON DELETE CASCADE;
    END IF;
    
    -- Add description
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='modules' AND COLUMN_NAME='description') THEN
        ALTER TABLE public.modules ADD COLUMN description text;
    END IF;
END $$;

-- 4. Fix Price column (Convert from numeric to text)
ALTER TABLE IF EXISTS public.courses ALTER COLUMN price TYPE text USING price::text;
ALTER TABLE IF EXISTS public.courses ALTER COLUMN price SET DEFAULT '0';

-- 5. Set up RLS for Chapters
ALTER TABLE public.chapters ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Chapters are viewable by everyone" ON public.chapters;
CREATE POLICY "Chapters are viewable by everyone" ON public.chapters FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admins can manage chapters" ON public.chapters;
CREATE POLICY "Admins can manage chapters" ON public.chapters 
FOR ALL USING (
  EXISTS (
    SELECT 1 FROM profiles 
    WHERE profiles.id = auth.uid() 
    AND profiles.role = 'Admin'
  )
);
